spring:
  datasource:
    username: HYHIS
    password: hyhis
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #jdbc-url: jdbc:oracle:thin:@10.53.86.200:1521/ORCL
    url: jdbc:oracle:thin:@10.0.0.3:1521:orcl
    type: com.alibaba.druid.pool.DruidDataSource

server:
  #端口号
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml


_defaultPayorID: 3
_defaultPlanID: 7
_defaultWxUserID: 999999
_defaultHsjcDrID: 319
_defaultHsjcDeptID: 54
_defaultHsjcGroupID: 17170
_defaultRecipeLimitDays: 1
_defaultWxPayID: 45
_defaultZfbPayID: 46
_defaultDgNshPayID: 47
_defaultChargeWin: 8
_noteJY: \u51ED\u53D1\u7968\u52302\u697C\u62BD\u8840\u5904\u62BD\u8840\u6216\u52302\u697C\u68C0\u9A8C\u79D1\u505A\u5316\u9A
_noteFS: \u51ED\u53D1\u7968\u52301\u697C\u653E\u5C04\u79D1\u62CD\u7247\u68C0\u67E5
_noteBC: \u51ED\u53D1\u7968\u52303\u697C\u8D85\u58F0\u8BCA\u65AD\u79D1\u505A\u68C0\u67E5